-- ============================================================================
-- ORBIT Investment Intelligence — Market Data from Snowflake Public Data (Paid)
-- ============================================================================
-- Creates tables in ORBIT_DEMO.MARKET_DATA from the near-real-time Paid listing.
-- All data is REAL — sourced from Cybersyn/Nasdaq/SEC/FRED/BIS/US Treasury.
-- ============================================================================

USE ROLE ORBIT_DEMO_ROLE;
USE DATABASE ORBIT_DEMO;
USE SCHEMA MARKET_DATA;
USE WAREHOUSE ORBIT_DEMO_WH;

-- ---------------------------------------------------------------------------
-- 1. FACT_STOCK_PRICES — Daily OHLCV for demo securities
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_STOCK_PRICES AS
WITH price_data AS (
    SELECT
        TICKER,
        DATE AS PRICE_DATE,
        VARIABLE,
        VALUE
    FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.STOCK_PRICE_TIMESERIES
    WHERE DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
      AND TICKER IN (SELECT TICKER FROM ORBIT_DEMO.CURATED.DIM_ISSUER)
),
pivoted AS (
    SELECT
        TICKER,
        PRICE_DATE,
        MAX(CASE WHEN VARIABLE = 'pre-market_open' THEN VALUE END) AS PRICE_OPEN,
        MAX(CASE WHEN VARIABLE = 'post-market_close' THEN VALUE END) AS PRICE_CLOSE,
        MAX(CASE WHEN VARIABLE = 'all-day_high' THEN VALUE END) AS PRICE_HIGH,
        MAX(CASE WHEN VARIABLE = 'all-day_low' THEN VALUE END) AS PRICE_LOW,
        MAX(CASE WHEN VARIABLE = 'nasdaq_volume' THEN VALUE END) AS VOLUME
    FROM price_data
    GROUP BY TICKER, PRICE_DATE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY i.ISSUER_ID, p.PRICE_DATE) AS PRICE_ID,
    i.ISSUER_ID,
    i.TICKER,
    i.COMPANY_NAME,
    i.GICS_SECTOR,
    p.PRICE_DATE,
    p.PRICE_OPEN,
    p.PRICE_HIGH,
    p.PRICE_LOW,
    p.PRICE_CLOSE,
    p.VOLUME::BIGINT AS VOLUME,
    'SNOWFLAKE_PUBLIC_DATA_PAID' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM pivoted p
JOIN ORBIT_DEMO.CURATED.DIM_ISSUER i ON p.TICKER = i.TICKER
WHERE p.PRICE_CLOSE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. FACT_SEC_FINANCIALS — Income statement, balance sheet, cash flow from XBRL
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_SEC_FINANCIALS AS
WITH our_companies AS (
    SELECT ISSUER_ID, CIK, TICKER, COMPANY_NAME, GICS_SECTOR
    FROM ORBIT_DEMO.CURATED.DIM_ISSUER
    WHERE CIK IS NOT NULL
),
sec_raw AS (
    SELECT
        CIK, ADSH, TAG, MEASURE_DESCRIPTION, PERIOD_END_DATE, COVERED_QTRS,
        TRY_CAST(VALUE AS FLOAT) AS VALUE_NUM, UNIT
    FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_CORPORATE_REPORT_ATTRIBUTES
    WHERE CIK IN (SELECT CIK FROM our_companies)
      AND PERIOD_END_DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
      AND VALUE IS NOT NULL
      AND TRY_CAST(VALUE AS FLOAT) IS NOT NULL
      AND TAG IN (
          'Revenues', 'RevenueFromContractWithCustomerExcludingAssessedTax',
          'NetIncomeLoss', 'GrossProfit', 'OperatingIncomeLoss',
          'EarningsPerShareBasic', 'EarningsPerShareDiluted',
          'ResearchAndDevelopmentExpense', 'InterestExpense',
          'Assets', 'Liabilities', 'StockholdersEquity',
          'CashAndCashEquivalentsAtCarryingValue', 'LongTermDebt',
          'NetCashProvidedByUsedInOperatingActivities',
          'NetCashProvidedByUsedInFinancingActivities',
          'PaymentsToAcquirePropertyPlantAndEquipment',
          'DepreciationDepletionAndAmortization',
          'EntityCommonStockSharesOutstanding',
          'WeightedAverageNumberOfSharesOutstandingBasic'
      )
),
pivoted AS (
    SELECT
        CIK, ADSH, PERIOD_END_DATE, COVERED_QTRS,
        CASE
            WHEN COVERED_QTRS = 1 THEN 'Q'
            WHEN COVERED_QTRS = 2 THEN 'H1'
            WHEN COVERED_QTRS = 3 THEN 'Q3_YTD'
            WHEN COVERED_QTRS = 4 THEN 'FY'
            ELSE 'OTHER'
        END AS FISCAL_PERIOD,
        MAX(CASE WHEN TAG IN ('Revenues','RevenueFromContractWithCustomerExcludingAssessedTax') THEN VALUE_NUM END) AS REVENUE,
        MAX(CASE WHEN TAG = 'NetIncomeLoss' THEN VALUE_NUM END) AS NET_INCOME,
        MAX(CASE WHEN TAG = 'GrossProfit' THEN VALUE_NUM END) AS GROSS_PROFIT,
        MAX(CASE WHEN TAG = 'OperatingIncomeLoss' THEN VALUE_NUM END) AS OPERATING_INCOME,
        MAX(CASE WHEN TAG = 'EarningsPerShareBasic' THEN VALUE_NUM END) AS EPS_BASIC,
        MAX(CASE WHEN TAG = 'EarningsPerShareDiluted' THEN VALUE_NUM END) AS EPS_DILUTED,
        MAX(CASE WHEN TAG = 'ResearchAndDevelopmentExpense' THEN VALUE_NUM END) AS RD_EXPENSE,
        MAX(CASE WHEN TAG = 'InterestExpense' THEN VALUE_NUM END) AS INTEREST_EXPENSE,
        MAX(CASE WHEN TAG = 'Assets' THEN VALUE_NUM END) AS TOTAL_ASSETS,
        MAX(CASE WHEN TAG = 'Liabilities' THEN VALUE_NUM END) AS TOTAL_LIABILITIES,
        MAX(CASE WHEN TAG = 'StockholdersEquity' THEN VALUE_NUM END) AS TOTAL_EQUITY,
        MAX(CASE WHEN TAG = 'CashAndCashEquivalentsAtCarryingValue' THEN VALUE_NUM END) AS CASH_AND_EQUIVALENTS,
        MAX(CASE WHEN TAG = 'LongTermDebt' THEN VALUE_NUM END) AS LONG_TERM_DEBT,
        MAX(CASE WHEN TAG = 'NetCashProvidedByUsedInOperatingActivities' THEN VALUE_NUM END) AS OPERATING_CASH_FLOW,
        MAX(CASE WHEN TAG = 'NetCashProvidedByUsedInFinancingActivities' THEN VALUE_NUM END) AS FINANCING_CASH_FLOW,
        MAX(CASE WHEN TAG = 'PaymentsToAcquirePropertyPlantAndEquipment' THEN VALUE_NUM END) AS CAPEX,
        MAX(CASE WHEN TAG = 'DepreciationDepletionAndAmortization' THEN VALUE_NUM END) AS DEPRECIATION,
        MAX(CASE WHEN TAG IN ('EntityCommonStockSharesOutstanding','WeightedAverageNumberOfSharesOutstandingBasic') THEN VALUE_NUM END) AS SHARES_OUTSTANDING
    FROM sec_raw
    GROUP BY CIK, ADSH, PERIOD_END_DATE, COVERED_QTRS
),
deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY CIK, PERIOD_END_DATE, FISCAL_PERIOD
            ORDER BY
                CASE WHEN REVENUE IS NOT NULL THEN 1 ELSE 0 END +
                CASE WHEN NET_INCOME IS NOT NULL THEN 1 ELSE 0 END +
                CASE WHEN TOTAL_ASSETS IS NOT NULL THEN 1 ELSE 0 END DESC
        ) AS RN
    FROM pivoted
    WHERE REVENUE IS NOT NULL OR TOTAL_ASSETS IS NOT NULL OR OPERATING_CASH_FLOW IS NOT NULL
)
SELECT
    ROW_NUMBER() OVER (ORDER BY oc.ISSUER_ID, d.PERIOD_END_DATE DESC) AS FINANCIAL_ID,
    oc.ISSUER_ID, oc.TICKER, oc.COMPANY_NAME, oc.GICS_SECTOR,
    d.PERIOD_END_DATE, d.FISCAL_PERIOD,
    d.REVENUE, d.NET_INCOME, d.GROSS_PROFIT, d.OPERATING_INCOME,
    d.EPS_BASIC, d.EPS_DILUTED, d.RD_EXPENSE, d.INTEREST_EXPENSE,
    d.TOTAL_ASSETS, d.TOTAL_LIABILITIES, d.TOTAL_EQUITY,
    d.CASH_AND_EQUIVALENTS, d.LONG_TERM_DEBT,
    d.OPERATING_CASH_FLOW, d.FINANCING_CASH_FLOW, d.CAPEX, d.DEPRECIATION,
    d.SHARES_OUTSTANDING,
    -- Derived metrics
    CASE WHEN d.REVENUE > 0 THEN ROUND(d.GROSS_PROFIT / d.REVENUE * 100, 2) END AS GROSS_MARGIN_PCT,
    CASE WHEN d.REVENUE > 0 THEN ROUND(d.OPERATING_INCOME / d.REVENUE * 100, 2) END AS OPERATING_MARGIN_PCT,
    CASE WHEN d.REVENUE > 0 THEN ROUND(d.NET_INCOME / d.REVENUE * 100, 2) END AS NET_MARGIN_PCT,
    CASE WHEN d.TOTAL_EQUITY > 0 THEN ROUND(d.NET_INCOME / d.TOTAL_EQUITY * 100, 2) END AS ROE_PCT,
    CASE WHEN d.TOTAL_EQUITY > 0 THEN ROUND(d.LONG_TERM_DEBT / d.TOTAL_EQUITY, 3) END AS DEBT_TO_EQUITY,
    d.OPERATING_CASH_FLOW - ABS(COALESCE(d.CAPEX, 0)) AS FREE_CASH_FLOW,
    'SNOWFLAKE_PUBLIC_DATA_PAID' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM deduped d
JOIN our_companies oc ON d.CIK = oc.CIK
WHERE d.RN = 1
ORDER BY oc.ISSUER_ID, d.PERIOD_END_DATE DESC;

-- ---------------------------------------------------------------------------
-- 3. FACT_SEC_SEGMENTS — Revenue by geography/business segment
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_SEC_SEGMENTS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY i.ISSUER_ID, s.DATE DESC, s.VARIABLE_NAME) AS SEGMENT_ID,
    i.ISSUER_ID, i.TICKER, i.COMPANY_NAME, i.GICS_SECTOR,
    s.DATE AS PERIOD_END_DATE,
    s.VARIABLE_NAME AS SEGMENT_NAME,
    s.VALUE AS SEGMENT_REVENUE,
    'SNOWFLAKE_PUBLIC_DATA_PAID' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_METRICS_TIMESERIES s
JOIN ORBIT_DEMO.CURATED.DIM_ISSUER i ON s.COMPANY_ID = i.PROVIDER_COMPANY_ID
WHERE s.DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
  AND s.VALUE IS NOT NULL
  AND s.VALUE > 0;

-- ---------------------------------------------------------------------------
-- 4. FACT_TREASURY_YIELDS — US Treasury par yield curve
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_TREASURY_YIELDS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY t.DATE, a.VARIABLE_NAME) AS YIELD_ID,
    t.DATE,
    a.VARIABLE_NAME AS MATURITY_LABEL,
    CASE
        WHEN a.VARIABLE_NAME LIKE '%1 Mo%' THEN '1M'
        WHEN a.VARIABLE_NAME LIKE '%2 Mo%' THEN '2M'
        WHEN a.VARIABLE_NAME LIKE '%3 Mo%' THEN '3M'
        WHEN a.VARIABLE_NAME LIKE '%6 Mo%' THEN '6M'
        WHEN a.VARIABLE_NAME LIKE '%1 Yr%' THEN '1Y'
        WHEN a.VARIABLE_NAME LIKE '%2 Yr%' THEN '2Y'
        WHEN a.VARIABLE_NAME LIKE '%3 Yr%' THEN '3Y'
        WHEN a.VARIABLE_NAME LIKE '%5 Yr%' THEN '5Y'
        WHEN a.VARIABLE_NAME LIKE '%7 Yr%' THEN '7Y'
        WHEN a.VARIABLE_NAME LIKE '%10 Yr%' THEN '10Y'
        WHEN a.VARIABLE_NAME LIKE '%20 Yr%' THEN '20Y'
        WHEN a.VARIABLE_NAME LIKE '%30 Yr%' THEN '30Y'
        ELSE 'OTHER'
    END AS MATURITY_CODE,
    t.VALUE AS YIELD_PCT,
    'US_TREASURY' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.US_TREASURY_TIMESERIES t
JOIN SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.US_TREASURY_ATTRIBUTES a ON t.VARIABLE = a.VARIABLE
WHERE a.VARIABLE_NAME LIKE 'Treasury Par Yield Curve Rate%'
  AND t.DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
  AND t.VALUE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 5. FACT_ECONOMIC_INDICATORS — GDP, CPI, unemployment, fed funds
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_ECONOMIC_INDICATORS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY t.DATE, a.VARIABLE_NAME) AS INDICATOR_ID,
    t.DATE,
    'US' AS COUNTRY,
    a.VARIABLE_NAME AS INDICATOR_NAME,
    a.MEASURE,
    a.UNIT,
    t.VALUE,
    a.SEASONALLY_ADJUSTED,
    CASE
        WHEN UPPER(a.VARIABLE_NAME) LIKE '%GDP%' OR UPPER(a.MEASURE) LIKE '%GROSS DOMESTIC%' THEN 'GDP'
        WHEN UPPER(a.VARIABLE_NAME) LIKE '%CPI%' OR UPPER(a.MEASURE) LIKE '%CONSUMER PRICE%' THEN 'INFLATION'
        WHEN UPPER(a.VARIABLE_NAME) LIKE '%UNEMPLOYMENT%' THEN 'UNEMPLOYMENT'
        WHEN UPPER(a.VARIABLE_NAME) LIKE '%FED FUND%' THEN 'INTEREST_RATE'
        ELSE 'OTHER'
    END AS INDICATOR_CATEGORY,
    'FRED' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.FINANCIAL_ECONOMIC_INDICATORS_TIMESERIES t
JOIN SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES a
    ON t.VARIABLE = a.VARIABLE
WHERE t.DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
  AND t.VALUE IS NOT NULL
  AND (
      UPPER(a.VARIABLE_NAME) LIKE '%GDP%'
      OR UPPER(a.VARIABLE_NAME) LIKE '%CPI%'
      OR UPPER(a.VARIABLE_NAME) LIKE '%UNEMPLOYMENT%'
      OR UPPER(a.VARIABLE_NAME) LIKE '%FED FUND%'
      OR UPPER(a.MEASURE) LIKE '%CONSUMER PRICE%'
      OR UPPER(a.MEASURE) LIKE '%GROSS DOMESTIC PRODUCT%'
  );

-- ---------------------------------------------------------------------------
-- 6. FACT_POLICY_RATES — Central bank rates by country
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_POLICY_RATES AS
SELECT
    ROW_NUMBER() OVER (ORDER BY t.DATE DESC, a.VARIABLE_NAME) AS RATE_ID,
    t.DATE,
    a.VARIABLE_NAME AS RATE_NAME,
    a.GEO AS COUNTRY,
    t.VALUE AS RATE_PCT,
    a.UNIT,
    a.FREQUENCY,
    'BIS' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.BANK_FOR_INTERNATIONAL_SETTLEMENTS_TIMESERIES t
JOIN SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.BANK_FOR_INTERNATIONAL_SETTLEMENTS_ATTRIBUTES a
    ON t.VARIABLE = a.VARIABLE
WHERE UPPER(a.VARIABLE_NAME) LIKE '%POLICY%RATE%'
  AND t.DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
  AND t.VALUE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 7. FACT_FX_RATES — Major currency pairs vs USD
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_FX_RATES AS
SELECT
    ROW_NUMBER() OVER (ORDER BY DATE DESC, VARIABLE_NAME) AS FX_ID,
    DATE,
    VARIABLE_NAME AS CURRENCY_PAIR,
    QUOTE_CURRENCY_ID AS QUOTE_CURRENCY,
    BASE_CURRENCY_ID AS BASE_CURRENCY,
    VALUE AS EXCHANGE_RATE,
    'CYBERSYN' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.FX_RATES_TIMESERIES
WHERE BASE_CURRENCY_ID = 'USD'
  AND DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
  AND VALUE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 8. FACT_INSIDER_TRANSACTIONS — SEC Form 4 filings
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_INSIDER_TRANSACTIONS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY sit.TRANSACTION_DATE DESC) AS INSIDER_TX_ID,
    i.ISSUER_ID,
    i.TICKER,
    i.COMPANY_NAME,
    sit.ISSUER_NAME,
    sit.FORM_TYPE,
    sit.TRANSACTION_DATE,
    sit.SECURITY_TITLE,
    sit.TRANSACTION_TYPE,
    sit.TRANSACTION_SHARES,
    sit.TRANSACTION_PRICE_PER_SHARE,
    sit.POST_TRANSACTION_SHARES_OWNED,
    sit.OWNERSHIP,
    'SEC_FORM4' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_INSIDER_TRADING_SECURITIES_INDEX sit
JOIN ORBIT_DEMO.CURATED.DIM_ISSUER i ON sit.ISSUER_CIK = i.CIK
WHERE sit.TRANSACTION_DATE >= DATEADD(YEAR, -3, CURRENT_DATE())
  AND sit.TRANSACTION_DATE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 9. FACT_INSTITUTIONAL_HOLDINGS — SEC 13F filings
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_INSTITUTIONAL_HOLDINGS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY idx.FILING_DATE DESC, att.PRIMARY_TICKER) AS HOLDING_ID,
    i.ISSUER_ID,
    i.TICKER,
    i.COMPANY_NAME,
    idx.FILING_MANAGER_NAME AS INSTITUTION_NAME,
    idx.FILING_DATE,
    att.MARKET_VALUE AS MARKET_VALUE_USD,
    att.NUMBER_OF_SHARES AS SHARES_HELD,
    att.INVESTMENT_DISCRETION,
    'SEC_13F' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_HOLDING_FILING_INDEX idx
JOIN SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_HOLDING_FILING_ATTRIBUTES att
    ON idx.ADSH = att.ADSH
JOIN ORBIT_DEMO.CURATED.DIM_ISSUER i ON att.PRIMARY_TICKER = i.TICKER
WHERE idx.FILING_DATE >= DATEADD(YEAR, -2, CURRENT_DATE());

-- ---------------------------------------------------------------------------
-- 10. FACT_COUNTRY_EMISSIONS — GHG emissions by country/sector
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_COUNTRY_EMISSIONS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY t.DATE DESC, a.VARIABLE_NAME) AS EMISSION_ID,
    t.DATE AS YEAR_DATE,
    a.VARIABLE_NAME AS INDICATOR_NAME,
    a.GEO AS COUNTRY,
    a.SECTOR,
    t.VALUE AS EMISSION_VALUE,
    a.UNIT,
    'CLIMATE_WATCH' AS DATA_SOURCE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.CLIMATE_WATCH_TIMESERIES t
JOIN SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.CLIMATE_WATCH_ATTRIBUTES a
    ON t.VARIABLE = a.VARIABLE
WHERE t.VALUE IS NOT NULL
  AND t.DATE >= DATEADD(YEAR, -10, CURRENT_DATE());
