-- ============================================================================
-- ORBIT Investment Intelligence — Cortex Search Services
-- ============================================================================
-- Creates corpus staging tables from real SEC filings and earnings transcripts,
-- then builds Cortex Search Services for RAG.
-- ============================================================================

USE ROLE ORBIT_DEMO_ROLE;
USE DATABASE ORBIT_DEMO;
USE WAREHOUSE ORBIT_DEMO_WH;

-- ---------------------------------------------------------------------------
-- 1. SEC Filing Text corpus (10-K, 10-Q, 8-K full text, chunked)
-- ---------------------------------------------------------------------------
USE SCHEMA RAW;

CREATE OR REPLACE TABLE SEC_FILING_TEXT (
    FILING_TEXT_ID INT AUTOINCREMENT,
    ISSUER_ID INT,
    CIK VARCHAR(20),
    TICKER VARCHAR(10),
    COMPANY_NAME VARCHAR(500),
    GICS_SECTOR VARCHAR(200),
    FILING_TYPE VARCHAR(20),
    FISCAL_YEAR INT,
    FISCAL_QUARTER VARCHAR(10),
    DOCUMENT_TITLE VARCHAR(1000),
    VARIABLE_NAME VARCHAR(500),
    PERIOD_END_DATE DATE,
    FILING_TEXT VARCHAR(16777216),
    TEXT_LENGTH INT,
    CHUNK_INDEX INT DEFAULT 0,
    DATA_SOURCE VARCHAR DEFAULT 'SNOWFLAKE_PUBLIC_DATA_PAID',
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Populate from SEC report text in the Paid share
-- Note: The exact source table name may vary; adjust if needed
INSERT INTO SEC_FILING_TEXT (
    ISSUER_ID, CIK, TICKER, COMPANY_NAME, GICS_SECTOR,
    FILING_TYPE, FISCAL_YEAR, FISCAL_QUARTER, DOCUMENT_TITLE,
    VARIABLE_NAME, PERIOD_END_DATE, FILING_TEXT, TEXT_LENGTH
)
SELECT
    i.ISSUER_ID,
    i.CIK,
    i.TICKER,
    i.COMPANY_NAME,
    i.GICS_SECTOR,
    CASE
        WHEN UPPER(a.VARIABLE_NAME) LIKE '%10-K%' THEN '10-K'
        WHEN UPPER(a.VARIABLE_NAME) LIKE '%10-Q%' THEN '10-Q'
        WHEN UPPER(a.VARIABLE_NAME) LIKE '%8-K%' THEN '8-K'
        ELSE 'OTHER'
    END AS FILING_TYPE,
    YEAR(t.DATE) AS FISCAL_YEAR,
    'Q' || QUARTER(t.DATE) AS FISCAL_QUARTER,
    i.COMPANY_NAME || ' - ' || a.VARIABLE_NAME || ' (' || t.DATE || ')' AS DOCUMENT_TITLE,
    a.VARIABLE_NAME,
    t.DATE AS PERIOD_END_DATE,
    t.VALUE::VARCHAR AS FILING_TEXT,
    LENGTH(t.VALUE::VARCHAR) AS TEXT_LENGTH
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_REPORT_TEXT_TIMESERIES t
JOIN SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_REPORT_TEXT_ATTRIBUTES a
    ON t.VARIABLE = a.VARIABLE
JOIN ORBIT_DEMO.CURATED.DIM_ISSUER i
    ON a.CIK = i.CIK
WHERE t.DATE >= DATEADD(YEAR, -2, CURRENT_DATE())
  AND t.VALUE IS NOT NULL
  AND LENGTH(t.VALUE::VARCHAR) > 100;

-- ---------------------------------------------------------------------------
-- 2. Earnings Transcripts corpus
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE EARNINGS_TRANSCRIPTS_CORPUS (
    TRANSCRIPT_ID INT AUTOINCREMENT,
    ISSUER_ID INT,
    TICKER VARCHAR(10),
    COMPANY_NAME VARCHAR(500),
    GICS_SECTOR VARCHAR(200),
    EVENT_TYPE VARCHAR(100),
    EVENT_DATE DATE,
    FISCAL_YEAR INT,
    FISCAL_PERIOD VARCHAR(10),
    DOCUMENT_TITLE VARCHAR(1000),
    DOCUMENT_TEXT VARCHAR(16777216),
    SPEAKER_NAME VARCHAR(500),
    SPEAKER_ROLE VARCHAR(200),
    SEGMENT_INDEX INT DEFAULT 0,
    DATA_SOURCE VARCHAR DEFAULT 'SNOWFLAKE_PUBLIC_DATA_PAID',
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Populate from company event transcripts
INSERT INTO EARNINGS_TRANSCRIPTS_CORPUS (
    ISSUER_ID, TICKER, COMPANY_NAME, GICS_SECTOR,
    EVENT_TYPE, EVENT_DATE, FISCAL_YEAR, FISCAL_PERIOD,
    DOCUMENT_TITLE, DOCUMENT_TEXT, SEGMENT_INDEX
)
SELECT
    i.ISSUER_ID,
    i.TICKER,
    i.COMPANY_NAME,
    i.GICS_SECTOR,
    t.EVENT_TYPE,
    t.EVENT_START_DATE AS EVENT_DATE,
    YEAR(t.EVENT_START_DATE) AS FISCAL_YEAR,
    'Q' || QUARTER(t.EVENT_START_DATE) AS FISCAL_PERIOD,
    i.COMPANY_NAME || ' ' || t.EVENT_TYPE || ' (' || t.EVENT_START_DATE || ')' AS DOCUMENT_TITLE,
    t.VALUE::VARCHAR AS DOCUMENT_TEXT,
    ROW_NUMBER() OVER (PARTITION BY i.TICKER, t.EVENT_START_DATE ORDER BY t.VARIABLE) AS SEGMENT_INDEX
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.COMPANY_EVENT_TRANSCRIPTS t
JOIN ORBIT_DEMO.CURATED.DIM_ISSUER i
    ON t.COMPANY_ID = i.PROVIDER_COMPANY_ID
WHERE t.EVENT_START_DATE >= DATEADD(YEAR, -2, CURRENT_DATE())
  AND t.VALUE IS NOT NULL
  AND LENGTH(t.VALUE::VARCHAR) > 50;

-- ---------------------------------------------------------------------------
-- 3. Cortex Search Service — SEC Filings
-- ---------------------------------------------------------------------------
USE SCHEMA AI;

CREATE OR REPLACE CORTEX SEARCH SERVICE ORBIT_SEC_FILINGS_SEARCH
    TEXT INDEXES DOCUMENT_TITLE, TICKER, COMPANY_NAME, GICS_SECTOR, FILING_TYPE
    VECTOR INDEXES FILING_TEXT (model = 'snowflake-arctic-embed-m-v1.5')
    ATTRIBUTES DOCUMENT_TITLE, TICKER, COMPANY_NAME, GICS_SECTOR, FILING_TYPE, FISCAL_YEAR, CIK, PERIOD_END_DATE
    WAREHOUSE = ORBIT_DEMO_SEARCH_WH
    TARGET_LAG = '1 day'
    AS
    SELECT
        FILING_TEXT_ID AS DOCUMENT_ID,
        DOCUMENT_TITLE,
        FILING_TEXT,
        TICKER,
        COMPANY_NAME,
        GICS_SECTOR,
        FILING_TYPE,
        FISCAL_YEAR,
        CIK,
        PERIOD_END_DATE
    FROM ORBIT_DEMO.RAW.SEC_FILING_TEXT
    WHERE FILING_TEXT IS NOT NULL
      AND TEXT_LENGTH > 100;

-- ---------------------------------------------------------------------------
-- 4. Cortex Search Service — Earnings Transcripts
-- ---------------------------------------------------------------------------
CREATE OR REPLACE CORTEX SEARCH SERVICE ORBIT_TRANSCRIPTS_SEARCH
    TEXT INDEXES DOCUMENT_TITLE, TICKER, COMPANY_NAME, GICS_SECTOR, EVENT_TYPE
    VECTOR INDEXES DOCUMENT_TEXT (model = 'snowflake-arctic-embed-m-v1.5')
    ATTRIBUTES DOCUMENT_TITLE, TICKER, COMPANY_NAME, GICS_SECTOR, EVENT_TYPE, FISCAL_YEAR, FISCAL_PERIOD, EVENT_DATE
    WAREHOUSE = ORBIT_DEMO_SEARCH_WH
    TARGET_LAG = '1 day'
    AS
    SELECT
        TRANSCRIPT_ID AS DOCUMENT_ID,
        DOCUMENT_TITLE,
        DOCUMENT_TEXT,
        TICKER,
        COMPANY_NAME,
        GICS_SECTOR,
        EVENT_TYPE,
        FISCAL_YEAR,
        FISCAL_PERIOD,
        EVENT_DATE
    FROM ORBIT_DEMO.RAW.EARNINGS_TRANSCRIPTS_CORPUS
    WHERE DOCUMENT_TEXT IS NOT NULL
      AND LENGTH(DOCUMENT_TEXT) > 50;
